### ISSUE TITLE
Mass upload of records

### ISSUE THREAD

**Issue by mnkykm** [glossm/api#42]
#27 에서 csv upload 는 해결했으나
Audio 또는 Video 를 한꺼번에 올리는 툴이 필요할듯 합니다.
최소 몇천개의 레코드를 올려야 합니다.

**Comment by mnkykm** [comment]
https://pypi.org/project/django-bulk-admin/
Not 100% automatic, but still better than now?

**Comment by mnkykm** [comment]
**settings.py**
```
PREREQ_APPS = [
    ...
    'bulk_admin',
]
```

**requirments.txt**
```
django-bulk-admin==0.1.1
```

**admin.py**
```
from bulk_admin import BulkModelAdmin
```

위와 같이 적용시켜 봤는데 아래와 같은 에러가 나네요.

```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/venv/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/venv/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/venv/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/venv/lib/python3.6/site-packages/bulk_admin/__init__.py", line 3, in <module>
    from bulk_admin.admin import (
  File "/venv/lib/python3.6/site-packages/bulk_admin/admin.py", line 12, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'
```

찾아보니 Django 1.9 이후로 `django.core.urlresolvers` 를 `django.urls` 로 옮겼다고 하는데 어떻게 해결하는 지는 모르겠네요 ㅎㅎ

**Comment by mnkykm** [comment]
다음과 같은 파형 이미지도 각 레코드마다 첨부하고자 합니다.

![04_dagur_01_0002](https://user-images.githubusercontent.com/26748682/41858611-461f4d6a-78d5-11e8-9c11-8898a0804e07.png)

이 이미지는 https://github.com/glossm/data/issues/8 에서 구현되면 wav 파일로부터 일괄적으로 생성될 것입니다.

**Comment by gunwooterry** [comment]
이건 라이브러리를 이용하는 것보다 Python script를 짜는 게 (현재로서는) 더 나은 해결책 같습니다.
나중에 관리자 페이지 client에서 bulk upload를 지원해 주는 게 좋을 것 같네요.

**Comment by mnkykm** [comment]
아 그렇군요? 그런 Python script 는 제가 짤 수 있을 것 같습니다. glossm/data 에서 작업하겠습니다.
+) 위에서 언급한 바와 같이 Record 모델에 파형 이미지를 위한 주소를 추가해야 할 것 같습니다.
